/**
 * store.ts — Zustand global state with Dexie.js hydration
 * Hydrates from IndexedDB on mount; all writes go to DB first, then update store.
 */

import { create } from "zustand";
import {
  getDB,
  todayStr,
  isoNow,
  calcStreak,
  detectBPTrend,
  type UserProfile,
  type HealthLog,
  type Medication,
  type MedicationLog,
  type ChatMessage,
  type TriageEvent,
  type Language,
} from "@/lib/db";

// ─── State Shape ──────────────────────────────────────────────────────────────

interface PulseCareState {
  // Hydration
  isHydrated: boolean;

  // User
  profile: UserProfile | null;

  // Today's snapshot
  todayLogs: HealthLog[];
  streak: number;

  // Medications
  medications: Medication[];
  todayMedLogs: MedicationLog[];

  // Chat
  chatMessages: ChatMessage[];
  chatLanguage: Language;

  // Triage history
  triageEvents: TriageEvent[];

  // Nudges (transient notifications generated by trend engine)
  activeNudge: string | null;

  // ─── Actions ──────────────────────────────────────────────────────────────

  /** Load everything from IndexedDB — call once on app boot */
  hydrate: () => Promise<void>;

  /** Save a new profile (creates or overwrites id=1) */
  saveProfile: (profile: Omit<UserProfile, "id" | "createdAt">) => Promise<void>;

  /** Update an existing profile field */
  updateProfile: (patch: Partial<UserProfile>) => Promise<void>;

  /** Add a health log entry and refresh today's snapshot */
  addHealthLog: (log: Omit<HealthLog, "id" | "createdAt">) => Promise<void>;

  /** Toggle a medication taken status for today */
  toggleMedication: (medicationId: number) => Promise<void>;

  /** Add a new medication to the list */
  addMedication: (med: Omit<Medication, "id" | "createdAt">) => Promise<void>;

  /** Append a chat message */
  addChatMessage: (msg: Omit<ChatMessage, "id" | "createdAt">) => Promise<void>;

  /** Clear all chat history */
  clearChat: () => Promise<void>;

  /** Set chat language */
  setChatLanguage: (lang: Language) => void;

  /** Save a triage event */
  addTriageEvent: (event: Omit<TriageEvent, "id" | "createdAt">) => Promise<void>;

  /** Dismiss the active nudge */
  dismissNudge: () => void;

  /** Run trend analysis and set nudge if needed */
  runTrendAnalysis: () => Promise<void>;
}

// ─── Store ────────────────────────────────────────────────────────────────────

export const usePulseCareStore = create<PulseCareState>((set, get) => ({
  isHydrated: false,
  profile: null,
  todayLogs: [],
  streak: 0,
  medications: [],
  todayMedLogs: [],
  chatMessages: [],
  chatLanguage: "en",
  triageEvents: [],
  activeNudge: null,

  // ─── hydrate ────────────────────────────────────────────────────────────────
  hydrate: async () => {
    if (typeof window === "undefined") return;
    const db = getDB();

    const [profileRow, todayLogs, medications, todayMedLogs, chatMessages, triageEvents] =
      await Promise.all([
        db.userProfile.get(1),
        db.healthLogs.where("date").equals(todayStr()).toArray(),
        db.medications.where("active").equals(1).toArray(),
        db.medicationLogs.where("date").equals(todayStr()).toArray(),
        db.chatHistory.orderBy("createdAt").limit(200).toArray(),
        db.triageEvents.orderBy("createdAt").reverse().limit(20).toArray(),
      ]);

    const streak = await calcStreak();

    set({
      profile: profileRow ?? null,
      todayLogs,
      streak,
      medications,
      todayMedLogs,
      chatMessages,
      chatLanguage: profileRow?.language ?? "en",
      triageEvents,
      isHydrated: true,
    });

    // Run trend analysis after hydration
    get().runTrendAnalysis();
  },

  // ─── saveProfile ─────────────────────────────────────────────────────────────
  saveProfile: async (data) => {
    const db = getDB();
    const profile: UserProfile = { id: 1, createdAt: isoNow(), ...data };
    await db.userProfile.put(profile);
    set({ profile, chatLanguage: profile.language });
  },

  // ─── updateProfile ────────────────────────────────────────────────────────────
  updateProfile: async (patch) => {
    const db = getDB();
    const current = get().profile;
    if (!current) return;
    const updated = { ...current, ...patch };
    await db.userProfile.put(updated);
    set({ profile: updated });
  },

  // ─── addHealthLog ─────────────────────────────────────────────────────────────
  addHealthLog: async (log) => {
    const db = getDB();
    const full: HealthLog = { ...log, createdAt: isoNow() };
    await db.healthLogs.add(full);

    // Refresh today's logs and streak
    const [todayLogs, streak] = await Promise.all([
      db.healthLogs.where("date").equals(todayStr()).toArray(),
      calcStreak(),
    ]);
    set({ todayLogs, streak });

    // Re-run trend analysis after new data
    get().runTrendAnalysis();
  },

  // ─── toggleMedication ────────────────────────────────────────────────────────
  toggleMedication: async (medicationId) => {
    const db = getDB();
    const today = todayStr();

    const existing = await db.medicationLogs
      .where("medicationId")
      .equals(medicationId)
      .and((l) => l.date === today)
      .first();

    if (existing?.id) {
      // Toggle existing
      const newTaken = !existing.taken;
      await db.medicationLogs.update(existing.id, {
        taken: newTaken,
        takenAt: newTaken ? isoNow() : undefined,
      });
    } else {
      // Create new log entry
      await db.medicationLogs.add({
        medicationId,
        date: today,
        taken: true,
        takenAt: isoNow(),
      });
    }

    const todayMedLogs = await db.medicationLogs
      .where("date")
      .equals(today)
      .toArray();
    set({ todayMedLogs });
  },

  // ─── addMedication ────────────────────────────────────────────────────────────
  addMedication: async (med) => {
    const db = getDB();
    await db.medications.add({ ...med, createdAt: isoNow() });
    const medications = await db.medications.where("active").equals(1).toArray();
    set({ medications });
  },

  // ─── addChatMessage ───────────────────────────────────────────────────────────
  addChatMessage: async (msg) => {
    const db = getDB();
    await db.chatHistory.add({ ...msg, createdAt: isoNow() });
    // Only keep last 200 messages in memory
    const chatMessages = await db.chatHistory.orderBy("createdAt").limit(200).toArray();
    set({ chatMessages });
  },

  // ─── clearChat ────────────────────────────────────────────────────────────────
  clearChat: async () => {
    const db = getDB();
    await db.chatHistory.clear();
    set({ chatMessages: [] });
  },

  // ─── setChatLanguage ──────────────────────────────────────────────────────────
  setChatLanguage: (lang) => {
    set({ chatLanguage: lang });
  },

  // ─── addTriageEvent ───────────────────────────────────────────────────────────
  addTriageEvent: async (event) => {
    const db = getDB();
    await db.triageEvents.add({ ...event, createdAt: isoNow() });
    const triageEvents = await db.triageEvents
      .orderBy("createdAt")
      .reverse()
      .limit(20)
      .toArray();
    set({ triageEvents });
  },

  // ─── dismissNudge ─────────────────────────────────────────────────────────────
  dismissNudge: () => set({ activeNudge: null }),

  // ─── runTrendAnalysis ────────────────────────────────────────────────────────
  runTrendAnalysis: async () => {
    if (typeof window === "undefined") return;
    const trend = await detectBPTrend();
    if (trend === "high") {
      set({
        activeNudge:
          "⚠️ Your blood pressure has been elevated for the last 3 days. Have you taken your prescribed medication today?",
      });
    }
  },
}));
